### ISSUE TITLE
standard introduces prefix confusion for iop ending in `/` or `#`

### ISSUE THREAD

**Issue by marc-portier** [i-adopt/ontology#11]
As things are being published now this vocabulary is totally introducing confusion on how to properly use it.

obviously there is a clear statement at [Line #3 of v1.0.0](https://github.com/i-adopt/ontology/blob/main/ontology/i-adopt_1_0_0.ttl#L3)
```turtle 
@prefix iop: <https://w3id.org/iadopt/ont/> .
```
in favor of the trailing `/` slash

But then there are the comments on [Line #117](https://github.com/i-adopt/ontology/blob/main/ontology/i-adopt_1_0_0.ttl#L117), [Line #125](https://github.com/i-adopt/ontology/blob/main/ontology/i-adopt_1_0_0.ttl#L125), [Line #134](https://github.com/i-adopt/ontology/blob/main/ontology/i-adopt_1_0_0.ttl#L134), [Line #142](https://github.com/i-adopt/ontology/blob/main/ontology/i-adopt_1_0_0.ttl#L142) and [Line #203](https://github.com/i-adopt/ontology/blob/main/ontology/i-adopt_1_0_0.ttl#L203) that suggest some properties and classes to belong to the `#` trailing (fragment identifier) space:

```turtle
###  https://w3id.org/iadopt/ont#«something»
:«something» rdf:type owl:ObjectProperty ;
```

To make matters worse the effective lines following those suggestive comments are in each of these cases actually placed relative to the `@base` on [Line #12](https://github.com/i-adopt/ontology/blob/main/ontology/i-adopt_1_0_0.ttl#L12) which ommits declaring its trailing preference:

``` turtle 
@base <https://w3id.org/iadopt/ont> .
```
this interesting combo in turn results to this odd outcome:

```bash
# find me the odd placed props and classes:
curl -s -L "https://w3id.org/iadopt/ont/" -H "Accept: text/turtle"|grep -P "^<.*iadopt/ont[^/].*>"
<https://w3id.org/iadopt/onthasApplicableContextObject> rdf:type owl:ObjectProperty ;
<https://w3id.org/iadopt/onthasApplicableMatrix> rdf:type owl:ObjectProperty ;
<https://w3id.org/iadopt/onthasApplicableObjectOfInterest> rdf:type owl:ObjectProperty ;
<https://w3id.org/iadopt/onthasApplicableProperty> rdf:type owl:ObjectProperty ;
<https://w3id.org/iadopt/ontVariableSet> rdf:type owl:Class ;

#find me the good ones
curl -s -L "https://w3id.org/iadopt/ont/" -H "Accept: text/turtle"|grep -P "^<.*iadopt/ont/.*>"
<https://w3id.org/iadopt/ont/constrains> rdf:type owl:ObjectProperty ;
<https://w3id.org/iadopt/ont/hasConstraint> rdf:type owl:ObjectProperty ;
<https://w3id.org/iadopt/ont/hasContextObject> rdf:type owl:ObjectProperty ;
<https://w3id.org/iadopt/ont/hasMatrix> rdf:type owl:ObjectProperty ;
<https://w3id.org/iadopt/ont/hasObjectOfInterest> rdf:type owl:ObjectProperty ;
<https://w3id.org/iadopt/ont/hasProperty> rdf:type owl:ObjectProperty ;
<https://w3id.org/iadopt/ont/Constraint> rdf:type owl:Class ;
<https://w3id.org/iadopt/ont/Entity> rdf:type owl:Class ;
<https://w3id.org/iadopt/ont/Property> rdf:type owl:Class ;
<https://w3id.org/iadopt/ont/Variable> rdf:type owl:Class ;

```

This  has already lead some adopters to use an own variant assuming the trailing `#` to be the more common used and thus intended pattern.

This is not how standards are building the trust needed for further consistent and fruitful use.
Please address at your earliest convenience!

To help out: as things are it really is hard to guess what the intentions were:
- should the five base-relative terms be indeed using #fragment identifiers as the comment suggests
- should they just all be relative to `iop:`

but I am opting for my own preference (more consistency - less surprise) here, and will thus provide a fix (PR) along the lines of option 2

**Comment by gwemon** [comment]
Hi @marc-portier, thanks for posting this issue. We'll look into it.

**Comment by SirkoS** [comment]
Hi @marc-portier,
thank you for spotting this and providing bugfix as well!
This was not intentional. As you can see, it only affects the concepts added in v1.0.0 and as such was a mistake while adding those.
I left another comment in the merge request. For a cleaner history, I would like to see that fixed before merging.

**Comment by marc-portier** [comment]
Makes sense. Will follow up accordingly. Thx for the feedback.

**Comment by SirkoS** [comment]
Changes are merged and published - thank you again!
