### ISSUE TITLE
Proposal to extend the I-ADOPT Framework to support the aggregation of I-ADOPT variables

### ISSUE THREAD

**Issue by gwemon** [i-adopt/ontology#8]
We are inviting comments to our proposal to extend the I-ADOPT Framework to support the aggregation of I-ADOPT variables. Please see the [full text](https://www.rd-alliance.org/group/interoperable-descriptions-observable-property-terminology-wg-i-adopt-wg/wiki/proposal-extend) published on the RDA website and the associated [adoption stories](https://www.rd-alliance.org/group/interoperable-descriptions-observable-property-terminology-wg-i-adopt-wg/wiki/adoption-cases). You can also download the [proposal as pdf](https://github.com/i-adopt/ontology/blob/main/extensions/I-ADOPT%20extension%20proposal.pdf).

**Comment by dr-shorthair** [comment]
Is a `VariableSet` expected to be _generic_? I suspect each `VariableSet` will be tied to an application or domain.

**Comment by gwemon** [comment]
@dr-shorthair yes, the latter. Any I-ADOPT variable can belong to any number of VariableSet and VariableSet can be generic or specific depending on the use case, application or domain. We will provide some examples.

**Comment by gwemon** [comment]
Moving discussion with @graybeal to this issue ticket to keep it all together and avoid important discussion happening in a ticket that was already closed.
https://github.com/i-adopt/questions/issues/1#issuecomment-1469040493
https://github.com/i-adopt/questions/issues/1#issuecomment-1469459195
https://github.com/i-adopt/questions/issues/1#issuecomment-1470841333

**Comment by gwemon** [comment]
In response to your last comment @graybeal I think I understand what you mean now. Even though the new proposed properties "mirror" the existing I-ADOPT properties, only applicableObjectOfInterest and applicableProperty need to be defined by pointing to one or multiple concepts. So it will not reproduce the precision of the I-ADOPT variable composition but only focus on the elements that matter for the aggregation. By offering the options to describe the aggregation concepts using the applicable combination of one or multiple object of interests and one or multiple properties, we are enabling flexibility in grouping concepts and precision in defining the targeted variables according to a smaller number of criteria. For sure there might be cases when this is not desirable and there will be cases when hierarchical brd/nar relationships will be sufficient but when it is necessary to define precise criteria for aggregation then the proposed extension to the I-ADOPT framework will enable this.

**Comment by SirkoS** [comment]
@graybeal with respect to your comment [in the other issue](https://github.com/i-adopt/questions/issues/1#issuecomment-1469040493) I want to make sure I understand correctly:

is it fair to rephrase the three options you listed as follows:
* (A) ... this is pretty much doing the aggregation manually. so, I would pick all the variables that should belong to my variable set and assign them individually.
* (B) ... here I would provide constraints. those constraints describe which variables should belong into my set. for example, I could define everything which has an `ObjectOfInterest` of fish to be included in my `FishVariableSet`.
* (C) ... this would require a detailed semantic description of the definition of the set itself and its intention.

if my above understanding of your comment is correct, I think we're addressing options (B) and somewhat also (A). The current proposal allows you to define constraints using the `hasApplicable...` properties. all variables satisfying these constraints are then included in the respective set. this does (as of now) not allow to define more detailed constraints than like "each variable of this set needs to have an `ObjectOfInterest` of A or B or C and a `Property` of X or Y or Z". More detailed could mean "it needs tuples of `(ObjectOfInterest, Property)` of (A,X) or (B,Y) or (C,Z)".

We would also support option A by using RO's `memberOf` relation. Although, personally I think this is less preferred as it would imply constant maintenance of a VariableSet to keep it up to date with newly added Variables whereas with (B) this could be updated by an automated system.

**Comment by gwemon** [comment]
The proposed extension has been implemented with some modifications taking into account feedback received, in a new version of the ontology: https://i-adopt.github.io/ and this ticket can now be closed.
